/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const PlaylistsLazyImport = createFileRoute('/playlists')()

// Create/Update Routes

const PlaylistsLazyRoute = PlaylistsLazyImport.update({
  path: '/playlists',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/playlists.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/playlists': {
      preLoaderRoute: typeof PlaylistsLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([IndexRoute, PlaylistsLazyRoute])

/* prettier-ignore-end */
