// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const SpillelisterLazyImport = createFileRoute('/spillelister')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const SpillelisterLazyRoute = SpillelisterLazyImport.update({
  path: '/spillelister',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/spillelister.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/spillelister': {
      preLoaderRoute: typeof SpillelisterLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  SpillelisterLazyRoute,
])
